// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Context;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Comuna> Comuna { get; set; }

    public virtual DbSet<Departamento> Departamento { get; set; }

    public virtual DbSet<DepartamentoPropietario> DepartamentoPropietario { get; set; }

    public virtual DbSet<ModeloDepartamento> ModeloDepartamento { get; set; }

    public virtual DbSet<Orientacion> Orientacion { get; set; }

    public virtual DbSet<Propietario> Propietario { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=(localdb)\\mssqllocaldb;Initial Catalog=master;Integrated Security=True;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Comuna>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Comuna__3214EC07501139DA");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Departamento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Departam__3214EC07F83C780E");

            entity.HasIndex(e => new { e.Direccion, e.Numero }, "UQ_Departamento_Direccion_Numero").IsUnique();

            entity.Property(e => e.Direccion)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.NumeracionDireccion)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Numero)
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<DepartamentoPropietario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Departam__3214EC0706917F85");

            entity.Property(e => e.PorcentajePropiedad).HasColumnType("decimal(5, 2)");
        });

        modelBuilder.Entity<ModeloDepartamento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ModeloDe__3214EC0794F11C35");

            entity.Property(e => e.Nombre)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Orientacion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Orientac__3214EC07D2019F8E");

            entity.Property(e => e.Nombre)
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Propietario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Propieta__3214EC076FCC74DC");

            entity.Property(e => e.Correo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Dv)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("DV");
            entity.Property(e => e.FechaNacimiento).HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Rut)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}