// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Context;

public partial class Departamento
{
    public long Id { get; set; }

    public string Numero { get; set; }

    public int? CantidadBanos { get; set; }

    public int? CantidadDormitorios { get; set; }

    public int? IdOrientacion { get; set; }

    public int? IdModelo { get; set; }

    public int? PrecioArriendo { get; set; }

    public int? PrecioGastoComun { get; set; }

    public string Direccion { get; set; }

    public string NumeracionDireccion { get; set; }

    public int? IdComuna { get; set; }
}