// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Context;

public partial class DepartamentoPropietario
{
    public long IdDepartamento { get; set; }

    public long IdPropietario { get; set; }

    public decimal? PorcentajePropiedad { get; set; }

    public long Id { get; set; }
}