// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Context;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Context
{
    public partial interface IContextProcedures
    {
        Task<int> sp_AsignarUnidadAsync(long? idPropietario, long? idDepartamento, decimal? porcentajePropiedad, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_BuscarDepartamentosResult>> sp_BuscarDepartamentosAsync(string palabraClave, string rUT, string numeroUnidad, string ubicacion, int? numeroPagina, int? tamanoPagina, OutputParameter<int?> totalCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_BuscarDepartamentos_TodosResult>> sp_BuscarDepartamentos_TodosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_RegistrarDepartamentoAsync(string numero, int? idOrientacion, string direccion, string numeracionDireccion, int? idComuna, int? cantidadDormitorios, int? cantidadBanos, int? precioArriendo, int? precioGastoComun, int? idTipoCocina, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_RegistrarPropietario_AsignarUnidadResult>> sp_RegistrarPropietario_AsignarUnidadAsync(string rut, string dv, string nombre, DateTime? fechaNacimiento, string correoElectronico, long? idDepartamento, decimal? porcentajePropiedad, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
