// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Context;

public partial class ModeloDepartamento
{
    public int Id { get; set; }

    public string Nombre { get; set; }
}