// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Context;

public partial class Propietario
{
    public long Id { get; set; }

    public string Rut { get; set; }

    public string Nombre { get; set; }

    public DateTime? FechaNacimiento { get; set; }

    public string Correo { get; set; }

    public string Dv { get; set; }
}