// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Context
{
    public partial class sp_BuscarDepartamentosResult
    {
        public int? DepartamentoId { get; set; }
        [StringLength(2147483647)]
        public string DireccionCompleta { get; set; }
        [StringLength(10)]
        public string NumeroDepartamento { get; set; }
        [StringLength(100)]
        public string Orientacion { get; set; }
        [StringLength(100)]
        public string Modelo { get; set; }
        public int? CantidadDormitorios { get; set; }
        public int? CantidadBanos { get; set; }
        public int? PrecioArriendo { get; set; }
        public int? PrecioGastoComun { get; set; }
        [StringLength(2147483647)]
        public string Propietarios { get; set; }
        [StringLength(2147483647)]
        public string RutsPropietarios { get; set; }
    }
}
