// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Context
{
    public partial class sp_RegistrarPropietario_AsignarUnidadResult
    {
        public long? NuevoPropietarioId { get; set; }
    }
}
